# Generated by Django 5.0.6 on 2024-05-22 19:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=10, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 19, 39, 12, 51911, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_destination', models.CharField(max_length=100)),
                ('transferred', models.CharField(max_length=100)),
                ('travel_date', models.DateTimeField(blank=True, null=True)),
                ('payment_methods', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'BOLETO'), ('TRANSFERÊNCIA BANCÁRIA', 'TRANSFERÊNCIA BANCÁRIA'), ('CARTÃO DE CRÉDITO', 'CARTÃO DE CRÉDITO'), ('CARTÃO DE DÉBITO', 'CARTÃO DE DÉBITO'), ('BITCOIN OU CRIPTOMOEDAS', 'BITCOIN OU CRIPTOMOEDAS')], max_length=30)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 19, 39, 12, 51911, tzinfo=datetime.timezone.utc))),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.clients_register')),
            ],
        ),
    ]
