# Generated by Django 5.0.6 on 2024-05-23 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_register',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 18, 56, 57, 686315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='clients_register',
            name='rg',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='trip_agenda',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 18, 56, 57, 686315, tzinfo=datetime.timezone.utc)),
        ),
    ]
