# Generated by Django 5.0.6 on 2024-05-23 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_alter_clients_register_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_agenda',
            old_name='id_paciente',
            new_name='id_client',
        ),
        migrations.AlterField(
            model_name='clients_register',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 20, 6, 4, 935650, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trip_agenda',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 20, 6, 4, 935650, tzinfo=datetime.timezone.utc)),
        ),
    ]
