# Generated by Django 5.0.6 on 2024-05-25 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0004_alter_clients_register_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_register',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 15, 54, 13, 56203, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='clients_register',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='trip_agenda',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 15, 54, 13, 57193, tzinfo=datetime.timezone.utc)),
        ),
    ]
