# Generated by Django 5.0.6 on 2024-05-25 19:32

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_alter_clients_register_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_register',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip_agenda',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 19, 32, 15, 912559, tzinfo=datetime.timezone.utc)),
        ),
    ]
