# Generated by Django 5.0.6 on 2024-05-25 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0006_alter_clients_register_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_agenda',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
